# Generated by Django 4.2.5 on 2023-10-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=3)),
                ('magnitud_terreno', models.CharField(choices=[('extenso', 'Extenso'), ('casero', 'Casero')], max_length=10)),
                ('ph_suelo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad_riego', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'requisitos',
            },
        ),
    ]
